<?php

declare(strict_types=1);

use App\Backend\Controllers\Shared\AccountSecurityController;
use App\Backend\Controllers\Shared\AuthController;
use App\Backend\Controllers\Admin\AdminAccountController;
use App\Backend\Controllers\Admin\AdminOrganizerChangeRequestController;
use App\Backend\Controllers\Admin\AdminSystemLogController;
use App\Backend\Controllers\Admin\AdminUserController;
use App\Backend\Controllers\Athlete\AthleteCompetitionLeaveController;
use App\Backend\Controllers\Athlete\AthleteIdentifierChangeController;
use App\Backend\Controllers\Athlete\AthleteLineupViewController;
use App\Backend\Controllers\Athlete\AthletePageController;
use App\Backend\Controllers\Athlete\AthletePersonalScheduleController;
use App\Backend\Controllers\Athlete\AthleteTeamInfoController;
use App\Backend\Controllers\Athlete\AthleteTeamInvitationController;
use App\Backend\Controllers\Coach\CoachAthleteAccountController;
use App\Backend\Controllers\Coach\CoachAthleteLeaveController;
use App\Backend\Controllers\Coach\CoachPageController;
use App\Backend\Controllers\Coach\CoachRegistrationController;
use App\Backend\Controllers\Coach\CoachTeamManagementController;
use App\Backend\Controllers\Coach\CoachTournamentRegistrationController;
use App\Backend\Controllers\Shared\DashboardController;
use App\Backend\Controllers\Shared\HomeController;
use App\Backend\Controllers\Organizer\OrganizerAthleteQualificationController;
use App\Backend\Controllers\Organizer\OrganizerCoachAccountController;
use App\Backend\Controllers\Organizer\OrganizerCoachQualificationController;
use App\Backend\Controllers\Organizer\OrganizerComplaintController;
use App\Backend\Controllers\Organizer\OrganizerHigherEligibilityController;
use App\Backend\Controllers\Organizer\OrganizerMatchResultController;
use App\Backend\Controllers\Organizer\OrganizerPersonalInfoChangeRequestController;
use App\Backend\Controllers\Organizer\OrganizerRankingController;
use App\Backend\Controllers\Organizer\OrganizerRefereeAccountController;
use App\Backend\Controllers\Organizer\OrganizerRefereeController;
use App\Backend\Controllers\Organizer\OrganizerScheduleController;
use App\Backend\Controllers\Organizer\OrganizerScheduleViewController;
use App\Backend\Controllers\Organizer\OrganizerTeamProfileController;
use App\Backend\Controllers\Organizer\OrganizerTournamentController;
use App\Backend\Controllers\Organizer\OrganizerVenueController;
use App\Backend\Controllers\Referee\RefereeAssignmentScheduleController;
use App\Backend\Controllers\Referee\RefereeIncidentReportController;
use App\Backend\Controllers\Referee\RefereeLeaveRequestController;
use App\Backend\Controllers\Referee\RefereeMatchSupervisionController;
use App\Backend\Controllers\Referee\RefereeRegistrationController;
use App\Backend\Core\Route\Router;

return static function (Router $router): void {
    $router->get('/', [HomeController::class, 'index']);

    $router->get('/login', [AuthController::class, 'showLogin']);
    $router->post('/login', [AuthController::class, 'login']);
    $router->post('/logout', [AuthController::class, 'logout'], ['auth']);

    $router->post('/api/auth/login', [AuthController::class, 'apiLogin']);
    $router->post('/api/auth/logout', [AuthController::class, 'apiLogout'], ['auth']);
    $router->get('/api/auth/me', [AuthController::class, 'apiMe'], ['auth']);
    $router->get('/tai-khoan/doi-mat-khau', [AccountSecurityController::class, 'page'], ['auth']);
    $router->get('/account/change-password', [AccountSecurityController::class, 'page'], ['auth']);
    $router->post('/api/account/password', [AccountSecurityController::class, 'changePassword'], ['auth']);
    $router->post('/api/auth/change-password', [AccountSecurityController::class, 'changePassword'], ['auth']);
    $router->get('/api/coach/register/options', [CoachRegistrationController::class, 'options']);
    $router->post('/api/auth/register/coach', [CoachRegistrationController::class, 'store']);
    $router->post('/api/register/coach', [CoachRegistrationController::class, 'store']);
    $router->post('/api/coach/register', [CoachRegistrationController::class, 'store']);
    $router->post('/api/coaches/register', [CoachRegistrationController::class, 'store']);
    $router->post('/api/huan-luyen-vien/register', [CoachRegistrationController::class, 'store']);
    $router->post('/api/huanluyenvien/register', [CoachRegistrationController::class, 'store']);
    $router->get('/coach/register', [CoachPageController::class, 'register']);
    $router->get('/huan-luyen-vien/dang-ky', [CoachPageController::class, 'register']);
    $router->get('/huanluyenvien/dang-ky', [CoachPageController::class, 'register']);
    $router->get('/api/referee/register/options', [RefereeRegistrationController::class, 'options']);
    $router->post('/api/auth/register/referee', [RefereeRegistrationController::class, 'store']);
    $router->post('/api/register/referee', [RefereeRegistrationController::class, 'store']);
    $router->post('/api/referee/register', [RefereeRegistrationController::class, 'store']);
    $router->post('/api/referees/register', [RefereeRegistrationController::class, 'store']);
    $router->post('/api/trong-tai/register', [RefereeRegistrationController::class, 'store']);
    $router->post('/api/trongtai/register', [RefereeRegistrationController::class, 'store']);
    $router->get('/referee/register', [RefereeRegistrationController::class, 'page']);
    $router->get('/trong-tai/dang-ky', [RefereeRegistrationController::class, 'page']);
    $router->get('/trongtai/dang-ky', [RefereeRegistrationController::class, 'page']);

    $router->get('/dashboard', [DashboardController::class, 'index'], ['auth']);
    $router->get('/admin', [DashboardController::class, 'admin'], ['auth', 'role:ADMIN']);
    $router->get('/admin/users', [AdminAccountController::class, 'page'], ['auth', 'role:ADMIN']);
    $router->get('/admin/nguoi-dung', [AdminUserController::class, 'page'], ['auth', 'role:ADMIN']);
    $router->get('/admin/logs', [AdminSystemLogController::class, 'page'], ['auth', 'role:ADMIN']);
    $router->get('/admin/xac-nhan-thong-tin-btc', [AdminOrganizerChangeRequestController::class, 'page'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/roles', [AdminAccountController::class, 'roles'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/accounts', [AdminAccountController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/accounts', [AdminAccountController::class, 'store'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/accounts/{id}', [AdminAccountController::class, 'show'], ['auth', 'role:ADMIN']);
    $router->add('PUT', '/api/admin/accounts/{id}', [AdminAccountController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->add('PATCH', '/api/admin/accounts/{id}', [AdminAccountController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/accounts/{id}/update', [AdminAccountController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->add('DELETE', '/api/admin/accounts/{id}', [AdminAccountController::class, 'destroy'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/accounts/{id}/delete', [AdminAccountController::class, 'destroy'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/users', [AdminUserController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/users/{id}', [AdminUserController::class, 'show'], ['auth', 'role:ADMIN']);
    $router->add('PUT', '/api/admin/users/{id}', [AdminUserController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->add('PATCH', '/api/admin/users/{id}', [AdminUserController::class, 'update'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/users/{id}/update', [AdminUserController::class, 'update'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/system-logs', [AdminSystemLogController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/system-logs/options', [AdminSystemLogController::class, 'options'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/system-logs/{id}', [AdminSystemLogController::class, 'show'], ['auth', 'role:ADMIN']);

    $router->get('/api/admin/organizer-change-requests', [AdminOrganizerChangeRequestController::class, 'index'], ['auth', 'role:ADMIN']);
    $router->get('/api/admin/organizer-change-requests/{id}', [AdminOrganizerChangeRequestController::class, 'show'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/organizer-change-requests/{id}/approve', [AdminOrganizerChangeRequestController::class, 'approve'], ['auth', 'role:ADMIN']);
    $router->post('/api/admin/organizer-change-requests/{id}/reject', [AdminOrganizerChangeRequestController::class, 'reject'], ['auth', 'role:ADMIN']);

    $router->get('/ban-to-chuc', [DashboardController::class, 'organizer'], ['auth', 'role:BAN_TO_CHUC,ADMIN']);
    $router->get('/ban-to-chuc/giai-dau', [OrganizerTournamentController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/doi-bong', [OrganizerTeamProfileController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/tu-cach-cap-tren', [OrganizerHigherEligibilityController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/trong-tai', [OrganizerRefereeController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/tai-khoan-hlv', [OrganizerCoachAccountController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/tai-khoan-trong-tai', [OrganizerRefereeAccountController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/huan-luyen-vien', [OrganizerCoachQualificationController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/van-dong-vien', [OrganizerAthleteQualificationController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/san-dau', [OrganizerVenueController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/lich-thi-dau', [OrganizerScheduleController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/khieu-nai', [OrganizerComplaintController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/ket-qua', [OrganizerMatchResultController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/xep-hang', [OrganizerRankingController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/ban-to-chuc/xac-nhan-thong-tin-ca-nhan', [OrganizerPersonalInfoChangeRequestController::class, 'page'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments', [OrganizerTournamentController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournament-options', [OrganizerTournamentController::class, 'options'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournament-eligibility-preview', [OrganizerTournamentController::class, 'eligibilityPreview'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/competition-locations', [OrganizerTournamentController::class, 'locations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments', [OrganizerTournamentController::class, 'store'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/update', [OrganizerTournamentController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/publish', [OrganizerTournamentController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/cancel', [OrganizerTournamentController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/registrations', [OrganizerTournamentController::class, 'registrations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/open', [OrganizerTournamentController::class, 'openRegistrations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/close', [OrganizerTournamentController::class, 'closeRegistrations'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/{registrationId}/approve', [OrganizerTournamentController::class, 'approveRegistration'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/{registrationId}/reject', [OrganizerTournamentController::class, 'rejectRegistration'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/registrations/{registrationId}/remove', [OrganizerTournamentController::class, 'removeRegistration'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/higher-eligibility', [OrganizerHigherEligibilityController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/higher-eligibility/review', [OrganizerHigherEligibilityController::class, 'review'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/higher-eligibility/mark', [OrganizerHigherEligibilityController::class, 'mark'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/higher-eligibility/{proposalId}/nominate', [OrganizerHigherEligibilityController::class, 'nominate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/higher-eligibility/{proposalId}/approve', [OrganizerHigherEligibilityController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/higher-eligibility/{proposalId}/reject', [OrganizerHigherEligibilityController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/teams', [OrganizerTeamProfileController::class, 'all'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/teams/{teamId}', [OrganizerTeamProfileController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/teams/{teamId}', [OrganizerTeamProfileController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/teams/{teamId}/update', [OrganizerTeamProfileController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/teams', [OrganizerTeamProfileController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/teams/{teamId}', [OrganizerTeamProfileController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/teams/{teamId}/cancel-participation', [OrganizerTeamProfileController::class, 'cancelParticipation'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referees', [OrganizerRefereeController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referees', [OrganizerRefereeController::class, 'store'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referee-matches', [OrganizerRefereeController::class, 'matches'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referee-leaves', [OrganizerRefereeController::class, 'leaves'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referee-assignments', [OrganizerRefereeController::class, 'assign'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referees/{refereeId}', [OrganizerRefereeController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referees/{refereeId}/assignments', [OrganizerRefereeController::class, 'assign'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referees/{refereeId}/leave', [OrganizerRefereeController::class, 'leave'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/coach-accounts', [OrganizerCoachAccountController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/coach-accounts/{accountId}', [OrganizerCoachAccountController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coach-accounts/{accountId}/approve', [OrganizerCoachAccountController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coach-accounts/{accountId}/reject', [OrganizerCoachAccountController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referee-accounts', [OrganizerRefereeAccountController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/referee-accounts/{accountId}', [OrganizerRefereeAccountController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referee-accounts/{accountId}/approve', [OrganizerRefereeAccountController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/referee-accounts/{accountId}/reject', [OrganizerRefereeAccountController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/coaches', [OrganizerCoachQualificationController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/coaches/{coachId}', [OrganizerCoachQualificationController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coaches/{coachId}/approve', [OrganizerCoachQualificationController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coaches/{coachId}/cancel-qualification', [OrganizerCoachQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/coaches/{coachId}/cancel', [OrganizerCoachQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/athletes', [OrganizerAthleteQualificationController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/athletes/{athleteId}', [OrganizerAthleteQualificationController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/approve-qualification', [OrganizerAthleteQualificationController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/approve', [OrganizerAthleteQualificationController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/cancel-qualification', [OrganizerAthleteQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/athletes/{athleteId}/cancel', [OrganizerAthleteQualificationController::class, 'cancel'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/venues', [OrganizerVenueController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues', [OrganizerVenueController::class, 'store'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/update', [OrganizerVenueController::class, 'update'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/deactivate', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/remove', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/venues/{venueId}', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/venues/{venueId}/delete', [OrganizerVenueController::class, 'deactivate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/schedule-view', [OrganizerScheduleViewController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/schedule-view/{matchId}', [OrganizerScheduleViewController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/match-schedule', [OrganizerScheduleViewController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/match-schedule/{matchId}', [OrganizerScheduleViewController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/ban-to-chuc/xem-lich-thi-dau', [OrganizerScheduleViewController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/ban-to-chuc/xem-lich-thi-dau/{matchId}', [OrganizerScheduleViewController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/schedules/tournaments', [OrganizerScheduleController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/schedule', [OrganizerScheduleController::class, 'summary'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/standard-schedule', [OrganizerScheduleController::class, 'generateStandardSchedule'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/schedule/generate-standard', [OrganizerScheduleController::class, 'generateStandardSchedule'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/groups', [OrganizerScheduleController::class, 'groups'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/groups', [OrganizerScheduleController::class, 'storeGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'group'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'updateGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'updateGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/groups/{groupId}/update', [OrganizerScheduleController::class, 'updateGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/tournaments/{id}/groups/{groupId}', [OrganizerScheduleController::class, 'deleteGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/groups/{groupId}/delete', [OrganizerScheduleController::class, 'deleteGroup'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/matches', [OrganizerScheduleController::class, 'matches'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/matches', [OrganizerScheduleController::class, 'storeMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'match'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'updateMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'updateMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/matches/{matchId}/update', [OrganizerScheduleController::class, 'updateMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/tournaments/{id}/matches/{matchId}', [OrganizerScheduleController::class, 'deleteMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/matches/{matchId}/delete', [OrganizerScheduleController::class, 'deleteMatch'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/complaints', [OrganizerComplaintController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/complaints/{complaintId}', [OrganizerComplaintController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/receive', [OrganizerComplaintController::class, 'receive'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/accept', [OrganizerComplaintController::class, 'receive'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/reject', [OrganizerComplaintController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/resolve', [OrganizerComplaintController::class, 'resolve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/no-process', [OrganizerComplaintController::class, 'noProcess'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/complaints/{complaintId}/ignore', [OrganizerComplaintController::class, 'noProcess'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/match-results', [OrganizerMatchResultController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/results', [OrganizerMatchResultController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/match-results/{resultId}', [OrganizerMatchResultController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/results/{resultId}', [OrganizerMatchResultController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/match-results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/match-results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PUT', '/api/organizer/results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('PATCH', '/api/organizer/results/{resultId}', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/match-results/{resultId}/adjust', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/match-results/{resultId}/update', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/results/{resultId}/adjust', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/results/{resultId}/update', [OrganizerMatchResultController::class, 'adjust'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/match-results/{resultId}/publish', [OrganizerMatchResultController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/results/{resultId}/publish', [OrganizerMatchResultController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/rankings/tournaments', [OrganizerRankingController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/standings/tournaments', [OrganizerRankingController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/rankings', [OrganizerRankingController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/standings', [OrganizerRankingController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/rankings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/rankings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/rankings/{rankingId}', [OrganizerRankingController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/standings/{rankingId}', [OrganizerRankingController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/rankings/{rankingId}/publish', [OrganizerRankingController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/standings/{rankingId}/publish', [OrganizerRankingController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/personal-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/profile-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/personal-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/organizer/profile-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/personal-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/profile-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/personal-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/profile-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/personal-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/profile-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/standings/tournaments', [OrganizerRankingController::class, 'tournaments'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/standings', [OrganizerRankingController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/tournaments/{id}/standings/generate', [OrganizerRankingController::class, 'generate'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/standings/{rankingId}', [OrganizerRankingController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/standings/{rankingId}/publish', [OrganizerRankingController::class, 'publish'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/personal-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/profile-change-requests', [OrganizerPersonalInfoChangeRequestController::class, 'index'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/personal-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->get('/api/btc/profile-change-requests/{requestId}', [OrganizerPersonalInfoChangeRequestController::class, 'show'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/personal-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/profile-change-requests/{requestId}/approve', [OrganizerPersonalInfoChangeRequestController::class, 'approve'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/personal-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/profile-change-requests/{requestId}/reject', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/personal-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/btc/profile-change-requests/{requestId}/cancel', [OrganizerPersonalInfoChangeRequestController::class, 'reject'], ['auth', 'role:BAN_TO_CHUC']);
    $router->add('DELETE', '/api/organizer/tournaments/{id}', [OrganizerTournamentController::class, 'destroy'], ['auth', 'role:BAN_TO_CHUC']);
    $router->post('/api/organizer/tournaments/{id}/delete', [OrganizerTournamentController::class, 'destroy'], ['auth', 'role:BAN_TO_CHUC']);

    $router->get('/trong-tai', [DashboardController::class, 'referee'], ['auth', 'role:TRONG_TAI,ADMIN']);
    $router->get('/trong-tai/lich-phan-cong', [RefereeAssignmentScheduleController::class, 'page'], ['auth', 'role:TRONG_TAI']);
    $router->get('/trong-tai/giam-sat', [RefereeMatchSupervisionController::class, 'page'], ['auth', 'role:TRONG_TAI']);
    $router->get('/trong-tai/bao-cao-su-co', [RefereeIncidentReportController::class, 'page'], ['auth', 'role:TRONG_TAI']);
    $router->get('/trong-tai/xin-nghi-phep', [RefereeLeaveRequestController::class, 'page'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignment-schedule', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/match-assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/tournaments-of-me', [RefereeAssignmentScheduleController::class, 'tournaments'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/venues-of-me', [RefereeAssignmentScheduleController::class, 'venues'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incident-report-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/reportable-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incident-reports', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incidents', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incident-reports/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/incidents/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/leave-requests', [RefereeLeaveRequestController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/leaves', [RefereeLeaveRequestController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/time-off-requests', [RefereeLeaveRequestController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/leave-requests', [RefereeLeaveRequestController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/leaves', [RefereeLeaveRequestController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/time-off-requests', [RefereeLeaveRequestController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/leave-requests/{leaveId}', [RefereeLeaveRequestController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/leaves/{leaveId}', [RefereeLeaveRequestController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/time-off-requests/{leaveId}', [RefereeLeaveRequestController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/leave-requests/{leaveId}/cancel', [RefereeLeaveRequestController::class, 'cancel'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/leaves/{leaveId}/cancel', [RefereeLeaveRequestController::class, 'cancel'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/time-off-requests/{leaveId}/cancel', [RefereeLeaveRequestController::class, 'cancel'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/assignment-schedule/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/match-assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/matches/{matchId}', [RefereeAssignmentScheduleController::class, 'showMatch'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/matches/{matchId}/detail', [RefereeAssignmentScheduleController::class, 'matchDetail'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/matches/{matchId}/supervision', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/trongtai/supervision/matches/{matchId}', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/participants', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/supervision/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/assignments/{assignmentId}/confirm', [RefereeAssignmentScheduleController::class, 'confirm'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/trongtai/assignments/{assignmentId}/decline', [RefereeAssignmentScheduleController::class, 'decline'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/tournaments-of-me', [RefereeAssignmentScheduleController::class, 'tournaments'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/venues-of-me', [RefereeAssignmentScheduleController::class, 'venues'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incident-report-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/reportable-matches', [RefereeIncidentReportController::class, 'matches'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incident-reports', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incidents', [RefereeIncidentReportController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/incident-reports', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/incidents', [RefereeIncidentReportController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incident-reports/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/incidents/{reportId}', [RefereeIncidentReportController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/leave-requests', [RefereeLeaveRequestController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/leaves', [RefereeLeaveRequestController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/time-off-requests', [RefereeLeaveRequestController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/leave-requests', [RefereeLeaveRequestController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/leaves', [RefereeLeaveRequestController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/time-off-requests', [RefereeLeaveRequestController::class, 'store'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/leave-requests/{leaveId}', [RefereeLeaveRequestController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/leaves/{leaveId}', [RefereeLeaveRequestController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/time-off-requests/{leaveId}', [RefereeLeaveRequestController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/leave-requests/{leaveId}/cancel', [RefereeLeaveRequestController::class, 'cancel'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/leaves/{leaveId}/cancel', [RefereeLeaveRequestController::class, 'cancel'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/time-off-requests/{leaveId}/cancel', [RefereeLeaveRequestController::class, 'cancel'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/assignments/{assignmentId}/confirm', [RefereeAssignmentScheduleController::class, 'confirm'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/assignments/{assignmentId}/decline', [RefereeAssignmentScheduleController::class, 'decline'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignment-schedule', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/match-assignments', [RefereeAssignmentScheduleController::class, 'index'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/assignment-schedule/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/match-assignments/{assignmentId}', [RefereeAssignmentScheduleController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/matches/{matchId}', [RefereeAssignmentScheduleController::class, 'showMatch'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/matches/{matchId}/detail', [RefereeAssignmentScheduleController::class, 'matchDetail'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/matches/{matchId}/supervision', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/referee/supervision/matches/{matchId}', [RefereeMatchSupervisionController::class, 'show'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/participants', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/participants/confirm', [RefereeMatchSupervisionController::class, 'confirmParticipants'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/start', [RefereeMatchSupervisionController::class, 'start'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/pause', [RefereeMatchSupervisionController::class, 'pause'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/resume', [RefereeMatchSupervisionController::class, 'resume'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/result', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/results', [RefereeMatchSupervisionController::class, 'recordResult'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/finish', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->post('/api/referee/supervision/matches/{matchId}/end', [RefereeMatchSupervisionController::class, 'finish'], ['auth', 'role:TRONG_TAI']);
    $router->get('/api/coach/tournaments', [CoachTournamentRegistrationController::class, 'tournaments'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/tournament-registrations', [CoachTournamentRegistrationController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/registrations', [CoachTournamentRegistrationController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/tournament-registrations', [CoachTournamentRegistrationController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/tournaments/{tournamentId}/registrations', [CoachTournamentRegistrationController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/tournament-registrations/{registrationId}', [CoachTournamentRegistrationController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/registrations/{registrationId}', [CoachTournamentRegistrationController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/tournament-registrations/{registrationId}/cancel', [CoachTournamentRegistrationController::class, 'cancel'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/registrations/{registrationId}/cancel', [CoachTournamentRegistrationController::class, 'cancel'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/tournaments', [CoachTournamentRegistrationController::class, 'tournaments'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/tournament-registrations', [CoachTournamentRegistrationController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/registrations', [CoachTournamentRegistrationController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/tournament-registrations', [CoachTournamentRegistrationController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/tournaments/{tournamentId}/registrations', [CoachTournamentRegistrationController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/tournament-registrations/{registrationId}', [CoachTournamentRegistrationController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/registrations/{registrationId}', [CoachTournamentRegistrationController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/tournament-registrations/{registrationId}/cancel', [CoachTournamentRegistrationController::class, 'cancel'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/registrations/{registrationId}/cancel', [CoachTournamentRegistrationController::class, 'cancel'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/tournaments', [CoachTournamentRegistrationController::class, 'tournaments'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/tournament-registrations', [CoachTournamentRegistrationController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/registrations', [CoachTournamentRegistrationController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/tournament-registrations', [CoachTournamentRegistrationController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/tournaments/{tournamentId}/registrations', [CoachTournamentRegistrationController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/tournament-registrations/{registrationId}', [CoachTournamentRegistrationController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/registrations/{registrationId}', [CoachTournamentRegistrationController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/tournament-registrations/{registrationId}/cancel', [CoachTournamentRegistrationController::class, 'cancel'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/registrations/{registrationId}/cancel', [CoachTournamentRegistrationController::class, 'cancel'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/athletes', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/athlete-accounts', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/players', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/athletes', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/athlete-accounts', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/players', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/athletes', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/athlete-accounts', [CoachAthleteAccountController::class, 'store'], ['auth', 'role:HUAN_LUYEN_VIEN']);

    $router->get('/api/coach/teams', [CoachTeamManagementController::class, 'teams'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams', [CoachTeamManagementController::class, 'storeTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/teams/{teamId}', [CoachTeamManagementController::class, 'team'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PUT', '/api/coach/teams/{teamId}', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PATCH', '/api/coach/teams/{teamId}', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams/{teamId}/update', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/teams/{teamId}/members', [CoachTeamManagementController::class, 'members'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams/{teamId}/members', [CoachTeamManagementController::class, 'addMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams/{teamId}/members/{memberId}/remove', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams/{teamId}/members/{memberId}/delete', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams/{teamId}/members/{memberId}/transfer', [CoachTeamManagementController::class, 'transferMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/team-members/{memberId}/remove', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/team-members/{memberId}/delete', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/team-members/{memberId}/transfer', [CoachTeamManagementController::class, 'transferMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/teams/{teamId}/lineups', [CoachTeamManagementController::class, 'lineups'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/teams/{teamId}/lineups', [CoachTeamManagementController::class, 'storeLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/lineups', [CoachTeamManagementController::class, 'lineupList'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/lineups/{lineupId}', [CoachTeamManagementController::class, 'lineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PUT', '/api/coach/lineups/{lineupId}', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PATCH', '/api/coach/lineups/{lineupId}', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/lineups/{lineupId}/update', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/teams/{teamId}/schedule', [CoachTeamManagementController::class, 'schedule'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/teams/{teamId}/matches', [CoachTeamManagementController::class, 'schedule'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/results', [CoachTeamManagementController::class, 'results'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/match-results', [CoachTeamManagementController::class, 'results'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/results/{resultId}/complaints', [CoachTeamManagementController::class, 'complainResult'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/match-results/{resultId}/complaints', [CoachTeamManagementController::class, 'complainResult'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/athlete-change-requests', [CoachTeamManagementController::class, 'athleteChangeRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/athlete-profile-approvals', [CoachTeamManagementController::class, 'athleteChangeRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/profile-change-requests', [CoachTeamManagementController::class, 'athleteChangeRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/athlete-change-requests/{requestId}', [CoachTeamManagementController::class, 'athleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/profile-change-requests/{requestId}', [CoachTeamManagementController::class, 'athleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/athlete-change-requests/{requestId}/approve', [CoachTeamManagementController::class, 'approveAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/profile-change-requests/{requestId}/approve', [CoachTeamManagementController::class, 'approveAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/athlete-change-requests/{requestId}/reject', [CoachTeamManagementController::class, 'rejectAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/profile-change-requests/{requestId}/reject', [CoachTeamManagementController::class, 'rejectAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/athlete-leaves', [CoachAthleteLeaveController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/coach/athlete-leaves/{leaveId}', [CoachAthleteLeaveController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/athlete-leaves/{leaveId}/approve', [CoachAthleteLeaveController::class, 'approve'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/coach/athlete-leaves/{leaveId}/reject', [CoachAthleteLeaveController::class, 'reject'], ['auth', 'role:HUAN_LUYEN_VIEN']);

    $router->get('/api/huan-luyen-vien/teams', [CoachTeamManagementController::class, 'teams'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/teams', [CoachTeamManagementController::class, 'storeTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/teams/{teamId}', [CoachTeamManagementController::class, 'team'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PUT', '/api/huan-luyen-vien/teams/{teamId}', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PATCH', '/api/huan-luyen-vien/teams/{teamId}', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/teams/{teamId}/update', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/teams/{teamId}/members', [CoachTeamManagementController::class, 'members'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/teams/{teamId}/members', [CoachTeamManagementController::class, 'addMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/teams/{teamId}/members/{memberId}/remove', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/teams/{teamId}/members/{memberId}/transfer', [CoachTeamManagementController::class, 'transferMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/team-members/{memberId}/remove', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/team-members/{memberId}/transfer', [CoachTeamManagementController::class, 'transferMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/teams/{teamId}/lineups', [CoachTeamManagementController::class, 'lineups'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/teams/{teamId}/lineups', [CoachTeamManagementController::class, 'storeLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/lineups', [CoachTeamManagementController::class, 'lineupList'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/lineups/{lineupId}', [CoachTeamManagementController::class, 'lineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PUT', '/api/huan-luyen-vien/lineups/{lineupId}', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PATCH', '/api/huan-luyen-vien/lineups/{lineupId}', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/lineups/{lineupId}/update', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/teams/{teamId}/schedule', [CoachTeamManagementController::class, 'schedule'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/results', [CoachTeamManagementController::class, 'results'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/ket-qua', [CoachTeamManagementController::class, 'results'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/results/{resultId}/complaints', [CoachTeamManagementController::class, 'complainResult'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/ket-qua/{resultId}/khieu-nai', [CoachTeamManagementController::class, 'complainResult'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/athlete-change-requests', [CoachTeamManagementController::class, 'athleteChangeRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/athlete-change-requests/{requestId}', [CoachTeamManagementController::class, 'athleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/athlete-change-requests/{requestId}/approve', [CoachTeamManagementController::class, 'approveAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/athlete-change-requests/{requestId}/reject', [CoachTeamManagementController::class, 'rejectAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/don-nghi-phep-vdv', [CoachAthleteLeaveController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huan-luyen-vien/don-nghi-phep-vdv/{leaveId}', [CoachAthleteLeaveController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/don-nghi-phep-vdv/{leaveId}/duyet', [CoachAthleteLeaveController::class, 'approve'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huan-luyen-vien/don-nghi-phep-vdv/{leaveId}/tu-choi', [CoachAthleteLeaveController::class, 'reject'], ['auth', 'role:HUAN_LUYEN_VIEN']);

    $router->get('/api/huanluyenvien/teams', [CoachTeamManagementController::class, 'teams'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/teams', [CoachTeamManagementController::class, 'storeTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/teams/{teamId}', [CoachTeamManagementController::class, 'team'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PUT', '/api/huanluyenvien/teams/{teamId}', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PATCH', '/api/huanluyenvien/teams/{teamId}', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/teams/{teamId}/update', [CoachTeamManagementController::class, 'updateTeam'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/teams/{teamId}/members', [CoachTeamManagementController::class, 'members'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/teams/{teamId}/members', [CoachTeamManagementController::class, 'addMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/teams/{teamId}/members/{memberId}/remove', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/teams/{teamId}/members/{memberId}/transfer', [CoachTeamManagementController::class, 'transferMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/team-members/{memberId}/remove', [CoachTeamManagementController::class, 'removeMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/team-members/{memberId}/transfer', [CoachTeamManagementController::class, 'transferMember'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/teams/{teamId}/lineups', [CoachTeamManagementController::class, 'lineups'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/teams/{teamId}/lineups', [CoachTeamManagementController::class, 'storeLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/lineups', [CoachTeamManagementController::class, 'lineupList'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/lineups/{lineupId}', [CoachTeamManagementController::class, 'lineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PUT', '/api/huanluyenvien/lineups/{lineupId}', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->add('PATCH', '/api/huanluyenvien/lineups/{lineupId}', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/lineups/{lineupId}/update', [CoachTeamManagementController::class, 'updateLineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/teams/{teamId}/schedule', [CoachTeamManagementController::class, 'schedule'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/athlete-change-requests', [CoachTeamManagementController::class, 'athleteChangeRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/athlete-change-requests/{requestId}', [CoachTeamManagementController::class, 'athleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/athlete-change-requests/{requestId}/approve', [CoachTeamManagementController::class, 'approveAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/athlete-change-requests/{requestId}/reject', [CoachTeamManagementController::class, 'rejectAthleteChangeRequest'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/don-nghi-phep-vdv', [CoachAthleteLeaveController::class, 'index'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/api/huanluyenvien/don-nghi-phep-vdv/{leaveId}', [CoachAthleteLeaveController::class, 'show'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/don-nghi-phep-vdv/{leaveId}/duyet', [CoachAthleteLeaveController::class, 'approve'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->post('/api/huanluyenvien/don-nghi-phep-vdv/{leaveId}/tu-choi', [CoachAthleteLeaveController::class, 'reject'], ['auth', 'role:HUAN_LUYEN_VIEN']);

    $router->get('/api/athlete/team-invitations', [AthleteTeamInvitationController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/team-invitations/{invitationId}', [AthleteTeamInvitationController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/team-invitations/{invitationId}/accept', [AthleteTeamInvitationController::class, 'accept'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/team-invitations/{invitationId}/reject', [AthleteTeamInvitationController::class, 'reject'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/team-memberships/{memberId}/confirm', [AthleteTeamInvitationController::class, 'confirmMembership'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/teams', [AthleteTeamInfoController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/teams/{teamId}', [AthleteTeamInfoController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/lineups', [AthleteLineupViewController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/lineups/{lineupId}', [AthleteLineupViewController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/schedule', [AthletePersonalScheduleController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/matches', [AthletePersonalScheduleController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/matches/{matchId}', [AthletePersonalScheduleController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/identifier-change-requests', [AthleteIdentifierChangeController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/identifier-change-requests', [AthleteIdentifierChangeController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/identifier-change-requests/{requestId}', [AthleteIdentifierChangeController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/leave-requests', [AthleteCompetitionLeaveController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/leave-requests', [AthleteCompetitionLeaveController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/leave-requests/{leaveId}', [AthleteCompetitionLeaveController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/leave-requests/{leaveId}/cancel', [AthleteCompetitionLeaveController::class, 'cancel'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/athlete/competition-leaves', [AthleteCompetitionLeaveController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/athlete/competition-leaves', [AthleteCompetitionLeaveController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);

    $router->get('/api/player/invitations', [AthleteTeamInvitationController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/player/invitations/{invitationId}', [AthleteTeamInvitationController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/player/invitations/{invitationId}/accept', [AthleteTeamInvitationController::class, 'accept'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/player/invitations/{invitationId}/reject', [AthleteTeamInvitationController::class, 'reject'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/player/team/detail', [AthleteTeamInfoController::class, 'current'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/player/team/lineup', [AthleteLineupViewController::class, 'current'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/player/schedule/personal', [AthletePersonalScheduleController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/player/profile/change-id', [AthleteIdentifierChangeController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/player/leave-request', [AthleteCompetitionLeaveController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);

    $router->get('/api/van-dong-vien/loi-moi-doi-bong', [AthleteTeamInvitationController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/loi-moi-doi-bong/{invitationId}', [AthleteTeamInvitationController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/van-dong-vien/loi-moi-doi-bong/{invitationId}/accept', [AthleteTeamInvitationController::class, 'accept'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/van-dong-vien/loi-moi-doi-bong/{invitationId}/reject', [AthleteTeamInvitationController::class, 'reject'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/van-dong-vien/thanh-vien-doi-bong/{memberId}/confirm', [AthleteTeamInvitationController::class, 'confirmMembership'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/doi-bong', [AthleteTeamInfoController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/doi-bong/{teamId}', [AthleteTeamInfoController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/doi-hinh', [AthleteLineupViewController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/doi-hinh/{lineupId}', [AthleteLineupViewController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/lich-thi-dau', [AthletePersonalScheduleController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/tran-dau/{matchId}', [AthletePersonalScheduleController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/sua-id-ca-nhan', [AthleteIdentifierChangeController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/van-dong-vien/sua-id-ca-nhan', [AthleteIdentifierChangeController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/sua-id-ca-nhan/{requestId}', [AthleteIdentifierChangeController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/nghi-phep-thi-dau', [AthleteCompetitionLeaveController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/van-dong-vien/nghi-phep-thi-dau', [AthleteCompetitionLeaveController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/van-dong-vien/nghi-phep-thi-dau/{leaveId}', [AthleteCompetitionLeaveController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/van-dong-vien/nghi-phep-thi-dau/{leaveId}/cancel', [AthleteCompetitionLeaveController::class, 'cancel'], ['auth', 'role:VAN_DONG_VIEN']);

    $router->get('/api/vandongvien/team-invitations', [AthleteTeamInvitationController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/vandongvien/team-invitations/{invitationId}/accept', [AthleteTeamInvitationController::class, 'accept'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/vandongvien/team-invitations/{invitationId}/reject', [AthleteTeamInvitationController::class, 'reject'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/vandongvien/team-memberships/{memberId}/confirm', [AthleteTeamInvitationController::class, 'confirmMembership'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/teams', [AthleteTeamInfoController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/teams/{teamId}', [AthleteTeamInfoController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/lineups', [AthleteLineupViewController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/lineups/{lineupId}', [AthleteLineupViewController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/schedule', [AthletePersonalScheduleController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/matches/{matchId}', [AthletePersonalScheduleController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/identifier-change-requests', [AthleteIdentifierChangeController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/vandongvien/identifier-change-requests', [AthleteIdentifierChangeController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/identifier-change-requests/{requestId}', [AthleteIdentifierChangeController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/leave-requests', [AthleteCompetitionLeaveController::class, 'index'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/vandongvien/leave-requests', [AthleteCompetitionLeaveController::class, 'store'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/api/vandongvien/leave-requests/{leaveId}', [AthleteCompetitionLeaveController::class, 'show'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->post('/api/vandongvien/leave-requests/{leaveId}/cancel', [AthleteCompetitionLeaveController::class, 'cancel'], ['auth', 'role:VAN_DONG_VIEN']);

    $router->get('/huan-luyen-vien/van-dong-vien', [CoachPageController::class, 'players'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/giai-dau', [CoachPageController::class, 'tournaments'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/doi-bong', [CoachPageController::class, 'teamProfile'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/thanh-vien', [CoachPageController::class, 'members'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/doi-hinh', [CoachPageController::class, 'lineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/doi-hinh/chinh-sua', [CoachPageController::class, 'lineupEditor'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/lich-thi-dau-doi', [CoachPageController::class, 'teamSchedule'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/ket-qua', [CoachPageController::class, 'results'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien/yeu-cau-vdv', [CoachPageController::class, 'athleteRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/players', [CoachPageController::class, 'players'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/tournaments', [CoachPageController::class, 'tournaments'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/team', [CoachPageController::class, 'teamProfile'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/members', [CoachPageController::class, 'members'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/lineup', [CoachPageController::class, 'lineup'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/lineup-editor', [CoachPageController::class, 'lineupEditor'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/team-schedule', [CoachPageController::class, 'teamSchedule'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/results', [CoachPageController::class, 'results'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/coach/athlete-requests', [CoachPageController::class, 'athleteRequests'], ['auth', 'role:HUAN_LUYEN_VIEN']);
    $router->get('/huan-luyen-vien', [DashboardController::class, 'coach'], ['auth', 'role:HUAN_LUYEN_VIEN,ADMIN']);
    $router->get('/van-dong-vien/thong-bao', [AthletePageController::class, 'notifications'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/loi-moi-doi-bong', [AthletePageController::class, 'invitations'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/loi-moi-doi-bong/chi-tiet', [AthletePageController::class, 'invitationDetail'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/doi-bong-cua-toi', [AthletePageController::class, 'teamDetail'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/doi-hinh', [AthletePageController::class, 'lineupView'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/lich-thi-dau-ca-nhan', [AthletePageController::class, 'personalSchedule'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/ho-so', [AthletePageController::class, 'profile'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien/nghi-phep-thi-dau', [AthletePageController::class, 'leave'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/notifications', [AthletePageController::class, 'notifications'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/invitations', [AthletePageController::class, 'invitations'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/invitation-detail', [AthletePageController::class, 'invitationDetail'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/team', [AthletePageController::class, 'teamDetail'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/lineup', [AthletePageController::class, 'lineupView'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/schedule', [AthletePageController::class, 'personalSchedule'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/profile', [AthletePageController::class, 'profile'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/athlete/leave', [AthletePageController::class, 'leave'], ['auth', 'role:VAN_DONG_VIEN']);
    $router->get('/van-dong-vien', [DashboardController::class, 'athlete'], ['auth', 'role:VAN_DONG_VIEN,ADMIN']);
};

